const String supabaseUrl = 'https://ktkjtcjmsuugogyejtwh.supabase.co';
const String supabaseAnonKey =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0a2p0Y2ptc3V1Z29neWVqdHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwOTY3OTYsImV4cCI6MjA4ODY3Mjc5Nn0.Hu6cWispUu13a68lH8MzzAiVAePbZjqREPfFVfzed-8';

enum AppRoles { agent, superviseurNational, superviseurRegional }

const Map<String, String> superviseurRegionMap = {
  'SUPBOU-2026': 'BOULAOS',
  'SUPBAL-2026': 'BALBALA',
  'SUPRAS-2026': 'RAS DIKA',
};

// AGT-001 a AGT-413 => BV-001 a BV-413
String? getBureauForAgent(String agentCode) {
  final match = RegExp(r'^AGT-(\d{3})$').firstMatch(agentCode);
  if (match == null) return null;
  final num = int.parse(match.group(1)!);
  if (num >= 1 && num <= 413) return 'BV-' + num.toString().padLeft(3, '0');
  return null;
}

String? getCommuneForAgent(String agentCode) {
  final match = RegExp(r'^AGT-(\d{3})$').firstMatch(agentCode);
  if (match == null) return null;
  final num = int.parse(match.group(1)!);
  if (num >= 1 && num <= 15) return 'RAS DIKA';
  if (num >= 16 && num <= 217) return 'BOULAOS';
  if (num >= 218 && num <= 413) return 'BALBALA';
  return null;
}

const List<Map<String, String>> kBureauxFallback = [
  {'id': 'BV-001', 'nom': 'PREFECT DJIBOUTI -1', 'region': 'RAS DIKA', 'inscrits': '311'},
  {'id': 'BV-002', 'nom': 'PREFECT DJIBOUTI -2', 'region': 'RAS DIKA', 'inscrits': '311'},
  {'id': 'BV-003', 'nom': 'PREFECT DJIBOUTI -3', 'region': 'RAS DIKA', 'inscrits': '312'},
  {'id': 'BV-004', 'nom': 'ECOLE Z.P.S -1', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-005', 'nom': 'ECOLE Z.P.S -2', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-006', 'nom': 'ECOLE Z.P.S -3', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-007', 'nom': 'ECOLE Z.P.S -4', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-008', 'nom': 'ECOLE Z.P.S -5', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-009', 'nom': 'ECOLE Z.P.S -6', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-010', 'nom': 'ECOLE Z.P.S -7', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-011', 'nom': 'ECOLE Z.P.S -8', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-012', 'nom': 'ECOLE Z.P.S -9', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-013', 'nom': 'ECOLE Z.P.S -10', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-014', 'nom': 'ECOLE Z.P.S -11', 'region': 'RAS DIKA', 'inscrits': '395'},
  {'id': 'BV-015', 'nom': 'ECOLE Z.P.S -12', 'region': 'RAS DIKA', 'inscrits': '400'},
  {'id': 'BV-016', 'nom': 'ECOLE HADJI-DIDEH -1', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-017', 'nom': 'ECOLE HADJI-DIDEH -2', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-018', 'nom': 'ECOLE HADJI-DIDEH -3', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-019', 'nom': 'ECOLE HADJI-DIDEH -4', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-020', 'nom': 'ECOLE HADJI-DIDEH -5', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-021', 'nom': 'ECOLE HADJI-DIDEH -6', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-022', 'nom': 'ECOLE HADJI-DIDEH -7', 'region': 'BOULAOS', 'inscrits': '383'},
  {'id': 'BV-023', 'nom': 'ECOLE HADJI-DIDEH -8', 'region': 'BOULAOS', 'inscrits': '384'},
  {'id': 'BV-024', 'nom': 'PREMIER ARRONDT -1', 'region': 'BOULAOS', 'inscrits': '358'},
  {'id': 'BV-025', 'nom': 'PREMIER ARRONDT -2', 'region': 'BOULAOS', 'inscrits': '358'},
  {'id': 'BV-026', 'nom': 'PREMIER ARRONDT -3', 'region': 'BOULAOS', 'inscrits': '358'},
  {'id': 'BV-027', 'nom': 'PREMIER ARRONDT -4', 'region': 'BOULAOS', 'inscrits': '358'},
  {'id': 'BV-028', 'nom': 'PREMIER ARRONDT -5', 'region': 'BOULAOS', 'inscrits': '358'},
  {'id': 'BV-029', 'nom': 'CDC QUARTIER 3 -1', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-030', 'nom': 'CDC QUARTIER 3 -2', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-031', 'nom': 'CDC QUARTIER 3 -3', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-032', 'nom': 'CDC QUARTIER 3 -4', 'region': 'BOULAOS', 'inscrits': '410'},
  {'id': 'BV-033', 'nom': 'CDC QUARTIER 3 -5', 'region': 'BOULAOS', 'inscrits': '463'},
  {'id': 'BV-034', 'nom': 'CDC QUARTIER 3 -6', 'region': 'BOULAOS', 'inscrits': '463'},
  {'id': 'BV-035', 'nom': 'CDC QUARTIER 3 -7', 'region': 'BOULAOS', 'inscrits': '463'},
  {'id': 'BV-036', 'nom': 'CDC QUARTIER 3 -8', 'region': 'BOULAOS', 'inscrits': '466'},
  {'id': 'BV-037', 'nom': 'OVD -1', 'region': 'BOULAOS', 'inscrits': '291'},
  {'id': 'BV-038', 'nom': 'OVD -2', 'region': 'BOULAOS', 'inscrits': '291'},
  {'id': 'BV-039', 'nom': 'OVD -3', 'region': 'BOULAOS', 'inscrits': '291'},
  {'id': 'BV-040', 'nom': 'OVD -4', 'region': 'BOULAOS', 'inscrits': '293'},
  {'id': 'BV-041', 'nom': 'OVD -5', 'region': 'BOULAOS', 'inscrits': '489'},
  {'id': 'BV-042', 'nom': 'OVD -6', 'region': 'BOULAOS', 'inscrits': '489'},
  {'id': 'BV-043', 'nom': 'CDC QUARTIER 4 -1', 'region': 'BOULAOS', 'inscrits': '489'},
  {'id': 'BV-044', 'nom': 'CDC QUARTIER 4 -2', 'region': 'BOULAOS', 'inscrits': '490'},
  {'id': 'BV-045', 'nom': 'CDC QUARTIER 4 -3', 'region': 'BOULAOS', 'inscrits': '316'},
  {'id': 'BV-046', 'nom': 'CDC QUARTIER 4 -4', 'region': 'BOULAOS', 'inscrits': '316'},
  {'id': 'BV-047', 'nom': 'CDC QUARTIER 4 -5', 'region': 'BOULAOS', 'inscrits': '316'},
  {'id': 'BV-048', 'nom': 'CDC QUARTIER 4 -6', 'region': 'BOULAOS', 'inscrits': '316'},
  {'id': 'BV-049', 'nom': 'CDC QUARTIER 4 -7', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-050', 'nom': 'CDC QUARTIER 4 -8', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-051', 'nom': 'CHARIA CENTRALE -1', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-052', 'nom': 'CHARIA CENTRALE -2', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-053', 'nom': 'CHARIA CENTRALE -3', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-054', 'nom': 'CHARIA CENTRALE -4', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-055', 'nom': 'ECOLE EINGUELLA -1', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-056', 'nom': 'ECOLE EINGUELLA -2', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-057', 'nom': 'ECOLE EINGUELLA -3', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-058', 'nom': 'ECOLE EINGUELLA -4', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-059', 'nom': 'ECOLE EINGUELLA -5', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-060', 'nom': 'ECOLE EINGUELLA -6', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-061', 'nom': 'ECOLE EINGUELLA -7', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-062', 'nom': 'ECOLE EINGUELLA -8', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-063', 'nom': 'ECOLE EINGUELLA -9', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-064', 'nom': 'ECOLE EINGUELLA -10', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-065', 'nom': 'ECOLE EINGUELLA -11', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-066', 'nom': 'ECOLE EINGUELLA -12', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-067', 'nom': 'ECOLE EINGUELLA -13', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-068', 'nom': 'ECOLE EINGUELLA -14', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-069', 'nom': 'ECOLE EINGUELLA -15', 'region': 'BOULAOS', 'inscrits': '402'},
  {'id': 'BV-070', 'nom': 'ECOLE QUARTIER 5 -1', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-071', 'nom': 'ECOLE QUARTIER 5 -2', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-072', 'nom': 'ECOLE QUARTIER 5 -3', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-073', 'nom': 'ECOLE QUARTIER 5 -4', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-074', 'nom': 'ECOLE QUARTIER 5 -5', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-075', 'nom': 'ECOLE QUARTIER 5 -6', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-076', 'nom': 'ECOLE QUARTIER 5 -7', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-077', 'nom': 'ECOLE QUARTIER 5 -8', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-078', 'nom': 'ECOLE QUARTIER 5 -9', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-079', 'nom': 'ECOLE QUARTIER 5 -10', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-080', 'nom': 'ECOLE QUARTIER 5 -11', 'region': 'BOULAOS', 'inscrits': '406'},
  {'id': 'BV-081', 'nom': 'ECOLE CHATEAU DEAU -1', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-082', 'nom': 'ECOLE CHATEAU DEAU -2', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-083', 'nom': 'ECOLE CHATEAU DEAU -3', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-084', 'nom': 'ECOLE CHATEAU DEAU -4', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-085', 'nom': 'ECOLE CHATEAU DEAU -5', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-086', 'nom': 'ECOLE CHATEAU DEAU -6', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-087', 'nom': 'ECOLE CHATEAU DEAU -7', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-088', 'nom': 'ECOLE CHATEAU DEAU -8', 'region': 'BOULAOS', 'inscrits': '379'},
  {'id': 'BV-089', 'nom': 'ECOLE CHATEAU DEAU -9', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-090', 'nom': 'ECOLE QUARTIER 6 BIS -1', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-091', 'nom': 'ECOLE QUARTIER 6 BIS -2', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-092', 'nom': 'ECOLE QUARTIER 6 BIS -3', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-093', 'nom': 'ECOLE QUARTIER 6 BIS -4', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-094', 'nom': 'ECOLE QUARTIER 6 BIS -5', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-095', 'nom': 'ECOLE QUARTIER 6 BIS -6', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-096', 'nom': 'ECOLE QUARTIER 6 BIS -7', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-097', 'nom': 'ECOLE QUARTIER 6 BIS -8', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-098', 'nom': 'ECOLE QUARTIER 6 BIS -9', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-099', 'nom': 'ECOLE QUARTIER 6 BIS -10', 'region': 'BOULAOS', 'inscrits': '395'},
  {'id': 'BV-100', 'nom': 'ECOLE QUARTIER 6 BIS -11', 'region': 'BOULAOS', 'inscrits': '401'},
  {'id': 'BV-101', 'nom': 'ECOLE GACHAMALEH I -1', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-102', 'nom': 'ECOLE GACHAMALEH I -2', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-103', 'nom': 'ECOLE GACHAMALEH I -3', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-104', 'nom': 'ECOLE GACHAMALEH I -4', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-105', 'nom': 'ECOLE GACHAMALEH I -5', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-106', 'nom': 'ECOLE GACHAMALEH I -6', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-107', 'nom': 'ECOLE GACHAMALEH I -7', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-108', 'nom': 'ECOLE GACHAMALEH I -8', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-109', 'nom': 'ECOLE GACHAMALEH I -9', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-110', 'nom': 'ECOLE GACHAMALEH I -10', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-111', 'nom': 'ECOLE GACHAMALEH I -11', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-112', 'nom': 'ECOLE GACHAMALEH I -12', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-113', 'nom': 'ECOLE QUARTIER 7 -1', 'region': 'BOULAOS', 'inscrits': '408'},
  {'id': 'BV-114', 'nom': 'ECOLE QUARTIER 7 -2', 'region': 'BOULAOS', 'inscrits': '414'},
  {'id': 'BV-115', 'nom': 'ECOLE QUARTIER 7 -3', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-116', 'nom': 'ECOLE QUARTIER 7 -4', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-117', 'nom': 'ECOLE QUARTIER 7 -5', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-118', 'nom': 'ECOLE QUARTIER 7 -6', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-119', 'nom': 'ECOLE QUARTIER 7 -7', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-120', 'nom': 'ECOLE QUARTIER 7 -8', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-121', 'nom': 'ECOLE QUARTIER 7 -9', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-122', 'nom': 'ECOLE QUARTIER 7 -10', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-123', 'nom': 'ECOLE QUARTIER 7 -11', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-124', 'nom': 'ECOLE QUARTIER 7 -12', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-125', 'nom': 'ECOLE QUARTIER 7 -13', 'region': 'BOULAOS', 'inscrits': '392'},
  {'id': 'BV-126', 'nom': 'ECOLE QUARTIER 7 -14', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-127', 'nom': 'ECOLE GUELLEH BATAL I -1', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-128', 'nom': 'ECOLE GUELLEH BATAL I -2', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-129', 'nom': 'ECOLE GUELLEH BATAL I -3', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-130', 'nom': 'ECOLE GUELLEH BATAL I -4', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-131', 'nom': 'ECOLE GUELLEH BATAL I -5', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-132', 'nom': 'ECOLE GUELLEH BATAL I -6', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-133', 'nom': 'ECOLE GUELLEH BATAL I -7', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-134', 'nom': 'ECOLE GUELLEH BATAL I -8', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-135', 'nom': 'ECOLE GUELLEH BATAL I -9', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-136', 'nom': 'ECOLE GUELLEH BATAL I -10', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-137', 'nom': 'ECOLE GUELLEH BATAL I -11', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-138', 'nom': 'ECOLE GUELLEH BATAL I -12', 'region': 'BOULAOS', 'inscrits': '394'},
  {'id': 'BV-139', 'nom': 'ECOLE GUELLEH BATAL I -13', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-140', 'nom': 'ECOLE DU STADE I -1', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-141', 'nom': 'ECOLE DU STADE I -2', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-142', 'nom': 'ECOLE DU STADE I -3', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-143', 'nom': 'ECOLE DU STADE I -4', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-144', 'nom': 'ECOLE DU STADE I -5', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-145', 'nom': 'ECOLE DU STADE I -6', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-146', 'nom': 'ECOLE DU STADE I -7', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-147', 'nom': 'ECOLE ARHIBA I -1', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-148', 'nom': 'ECOLE ARHIBA I -2', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-149', 'nom': 'ECOLE ARHIBA I -3', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-150', 'nom': 'ECOLE ARHIBA I -4', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-151', 'nom': 'ECOLE ARHIBA I -5', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-152', 'nom': 'ECOLE ARHIBA I -6', 'region': 'BOULAOS', 'inscrits': '393'},
  {'id': 'BV-153', 'nom': 'ECOLE ARHIBA I -7', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-154', 'nom': 'ECOLE ARHIBA I -8', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-155', 'nom': 'ECOLE ARHIBA I -9', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-156', 'nom': 'ECOLE ARHIBA I -10', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-157', 'nom': 'ECOLE ARHIBA I -11', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-158', 'nom': 'ECOLE ARHIBA I -12', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-159', 'nom': 'ECOLE ARHIBA I -13', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-160', 'nom': 'ECOLE ARHIBA I -14', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-161', 'nom': 'ECOLE AL-HOURIYA I -1', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-162', 'nom': 'ECOLE AL-HOURIYA I -2', 'region': 'BOULAOS', 'inscrits': '398'},
  {'id': 'BV-163', 'nom': 'ECOLE AL-HOURIYA I -3', 'region': 'BOULAOS', 'inscrits': '403'},
  {'id': 'BV-164', 'nom': 'ECOLE AL-HOURIYA I -4', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-165', 'nom': 'ECOLE AL-HOURIYA I -5', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-166', 'nom': 'ECOLE AL-HOURIYA I -6', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-167', 'nom': 'ECOLE AL-HOURIYA I -7', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-168', 'nom': 'ECOLE AL-HOURIYA I -8', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-169', 'nom': 'ECOLE AL-HOURIYA I -9', 'region': 'BOULAOS', 'inscrits': '397'},
  {'id': 'BV-170', 'nom': 'ECOLE AL-HOURIYA I -10', 'region': 'BOULAOS', 'inscrits': '403'},
  {'id': 'BV-171', 'nom': 'CEM d\'Ambouli -1', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-172', 'nom': 'CEM d\'Ambouli -2', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-173', 'nom': 'CEM d\'Ambouli -3', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-174', 'nom': 'CEM d\'Ambouli -4', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-175', 'nom': 'CEM d\'Ambouli -5', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-176', 'nom': 'CEM d\'Ambouli -6', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-177', 'nom': 'CEM d\'Ambouli -7', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-178', 'nom': 'CEM d\'Ambouli -8', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-179', 'nom': 'CEM d\'Ambouli -9', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-180', 'nom': 'CEM d\'Ambouli -10', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-181', 'nom': 'CEM d\'Ambouli -11', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-182', 'nom': 'CEM d\'Ambouli -12', 'region': 'BOULAOS', 'inscrits': '411'},
  {'id': 'BV-183', 'nom': 'CEM d\'Ambouli -13', 'region': 'BOULAOS', 'inscrits': '417'},
  {'id': 'BV-184', 'nom': 'ECOLE GABODE V -1', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-185', 'nom': 'ECOLE GABODE V -2', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-186', 'nom': 'ECOLE GABODE V -3', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-187', 'nom': 'ECOLE GABODE V -4', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-188', 'nom': 'ECOLE GABODE V -5', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-189', 'nom': 'ECOLE GABODE V -6', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-190', 'nom': 'ECOLE GABODE V -7', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-191', 'nom': 'ECOLE GABODE V -8', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-192', 'nom': 'ECOLE GABODE V -9', 'region': 'BOULAOS', 'inscrits': '409'},
  {'id': 'BV-193', 'nom': 'ECOLE AMBOULI  I -1', 'region': 'BOULAOS', 'inscrits': '412'},
  {'id': 'BV-194', 'nom': 'ECOLE AMBOULI  I -2', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-195', 'nom': 'ECOLE AMBOULI  I -3', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-196', 'nom': 'ECOLE AMBOULI  I -4', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-197', 'nom': 'ECOLE AMBOULI  I -5', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-198', 'nom': 'ECOLE AMBOULI  I -6', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-199', 'nom': 'ECOLE AMBOULI  I -7', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-200', 'nom': 'ECOLE AMBOULI  I -8', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-201', 'nom': 'ECOLE AMBOULI  I -9', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-202', 'nom': 'ECOLE AMBOULI  I -10', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-203', 'nom': 'ECOLE AMBOULI II -1', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-204', 'nom': 'ECOLE AMBOULI II -2', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-205', 'nom': 'ECOLE AMBOULI II -3', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-206', 'nom': 'ECOLE AMBOULI II -4', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-207', 'nom': 'ECOLE AMBOULI II -5', 'region': 'BOULAOS', 'inscrits': '387'},
  {'id': 'BV-208', 'nom': 'ECOLE AMBOULI II -6', 'region': 'BOULAOS', 'inscrits': '401'},
  {'id': 'BV-209', 'nom': 'ECOLE AMBOULI II -7', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-210', 'nom': 'ECOLE AMBOULI II -8', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-211', 'nom': 'ECOLE AMBOULI II -9', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-212', 'nom': 'ECOLE AMBOULI II -10', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-213', 'nom': 'ECOLE AMBOULI II -11', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-214', 'nom': 'ECOLE AMBOULI II -12', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-215', 'nom': 'ECOLE AMBOULI II -13', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-216', 'nom': 'ECOLE AMBOULI II -14', 'region': 'BOULAOS', 'inscrits': '374'},
  {'id': 'BV-217', 'nom': 'ECOLE AMBOULI II -15', 'region': 'BOULAOS', 'inscrits': '375'},
  {'id': 'BV-218', 'nom': 'ECOLE BALBALA I -1', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-219', 'nom': 'ECOLE BALBALA I -2', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-220', 'nom': 'ECOLE BALBALA I -3', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-221', 'nom': 'ECOLE BALBALA I -4', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-222', 'nom': 'ECOLE BALBALA I -5', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-223', 'nom': 'ECOLE BALBALA I -6', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-224', 'nom': 'ECOLE BALBALA I -7', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-225', 'nom': 'ECOLE BALBALA I -8', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-226', 'nom': 'ECOLE BALBALA I -9', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-227', 'nom': 'ECOLE BALBALA I -10', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-228', 'nom': 'ECOLE BALBALA I -11', 'region': 'BALBALA', 'inscrits': '374'},
  {'id': 'BV-229', 'nom': 'ECOLE BALBALA I -12', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-230', 'nom': 'ECOLE PHARE -1', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-231', 'nom': 'ECOLE PHARE -2', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-232', 'nom': 'ECOLE PHARE -3', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-233', 'nom': 'ECOLE PHARE -4', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-234', 'nom': 'ECOLE PHARE -5', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-235', 'nom': 'ECOLE PHARE -6', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-236', 'nom': 'ECOLE PHARE -7', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-237', 'nom': 'ECOLE PHARE -8', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-238', 'nom': 'ECOLE PHARE -9', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-239', 'nom': 'ECOLE PHARE -10', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-240', 'nom': 'ECOLE PHARE -11', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-241', 'nom': 'ECOLE PHARE -12', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-242', 'nom': 'ECOLE PHARE -13', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-243', 'nom': 'ECOLE PHARE -14', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-244', 'nom': 'ECOLE PHARE -15', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-245', 'nom': 'ECOLE PHARE -16', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-246', 'nom': 'ECOLE PHARE -17', 'region': 'BALBALA', 'inscrits': '402'},
  {'id': 'BV-247', 'nom': 'ECOLE PHARE -18', 'region': 'BALBALA', 'inscrits': '411'},
  {'id': 'BV-248', 'nom': 'ECOLE BALBALA II -1', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-249', 'nom': 'ECOLE BALBALA II -2', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-250', 'nom': 'ECOLE BALBALA II -3', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-251', 'nom': 'ECOLE BALBALA II -4', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-252', 'nom': 'ECOLE BALBALA II -5', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-253', 'nom': 'ECOLE BALBALA II -6', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-254', 'nom': 'ECOLE BALBALA II -7', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-255', 'nom': 'ECOLE BALBALA II -8', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-256', 'nom': 'ECOLE BALBALA II -9', 'region': 'BALBALA', 'inscrits': '381'},
  {'id': 'BV-257', 'nom': 'ECOLE BALBALA II -10', 'region': 'BALBALA', 'inscrits': '386'},
  {'id': 'BV-258', 'nom': 'CEM HAYEL SAID -1', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-259', 'nom': 'CEM HAYEL SAID -2', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-260', 'nom': 'CEM HAYEL SAID -3', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-261', 'nom': 'CEM HAYEL SAID -4', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-262', 'nom': 'CEM HAYEL SAID -5', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-263', 'nom': 'CEM HAYEL SAID -6', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-264', 'nom': 'CEM HAYEL SAID -7', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-265', 'nom': 'CEM HAYEL SAID -8', 'region': 'BALBALA', 'inscrits': '403'},
  {'id': 'BV-266', 'nom': 'CEM HAYEL SAID -9', 'region': 'BALBALA', 'inscrits': '410'},
  {'id': 'BV-267', 'nom': 'ECOLE BALBALA III -1', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-268', 'nom': 'ECOLE BALBALA III -2', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-269', 'nom': 'ECOLE BALBALA III -3', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-270', 'nom': 'ECOLE BALBALA III -4', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-271', 'nom': 'ECOLE BALBALA III -5', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-272', 'nom': 'ECOLE BALBALA III -6', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-273', 'nom': 'ECOLE BALBALA III -7', 'region': 'BALBALA', 'inscrits': '416'},
  {'id': 'BV-274', 'nom': 'ECOLE BALBALA III -8', 'region': 'BALBALA', 'inscrits': '418'},
  {'id': 'BV-275', 'nom': 'ECOLE BALBALA VII -1', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-276', 'nom': 'ECOLE BALBALA VII -2', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-277', 'nom': 'ECOLE BALBALA VII -3', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-278', 'nom': 'ECOLE BALBALA VII -4', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-279', 'nom': 'ECOLE BALBALA VII -5', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-280', 'nom': 'ECOLE BALBALA VII -6', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-281', 'nom': 'ECOLE BALBALA VII -7', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-282', 'nom': 'ECOLE BALBALA VII -8', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-283', 'nom': 'ECOLE BALBALA VII -9', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-284', 'nom': 'ECOLE BALBALA VII -10', 'region': 'BALBALA', 'inscrits': '380'},
  {'id': 'BV-285', 'nom': 'ECOLE BALBALA VII -11', 'region': 'BALBALA', 'inscrits': '387'},
  {'id': 'BV-286', 'nom': 'ECOLE BALBALA VII bis -1', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-287', 'nom': 'ECOLE BALBALA VII bis -2', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-288', 'nom': 'ECOLE BALBALA VII bis -3', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-289', 'nom': 'ECOLE BALBALA VII bis -4', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-290', 'nom': 'ECOLE BALBALA VII bis -5', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-291', 'nom': 'ECOLE BALBALA VII bis -6', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-292', 'nom': 'ECOLE BALBALA VII bis -7', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-293', 'nom': 'ECOLE BALBALA VII bis -8', 'region': 'BALBALA', 'inscrits': '412'},
  {'id': 'BV-294', 'nom': 'ECOLE BALBALA VII bis -9', 'region': 'BALBALA', 'inscrits': '415'},
  {'id': 'BV-295', 'nom': 'ECOLE PK 12 -1', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-296', 'nom': 'ECOLE PK 12 -2', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-297', 'nom': 'ECOLE PK 12 -3', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-298', 'nom': 'ECOLE PK 12 -4', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-299', 'nom': 'ECOLE PK 12 -5', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-300', 'nom': 'ECOLE PK 12 -6', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-301', 'nom': 'ECOLE PK 12 -7', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-302', 'nom': 'ECOLE PK 12 -8', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-303', 'nom': 'ECOLE PK 12 -9', 'region': 'BALBALA', 'inscrits': '378'},
  {'id': 'BV-304', 'nom': 'ECOLE PK 12 -10', 'region': 'BALBALA', 'inscrits': '387'},
  {'id': 'BV-305', 'nom': 'ECOLE PK 14 -1', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-306', 'nom': 'ECOLE PK 14 -2', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-307', 'nom': 'ECOLE PK 14 -3', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-308', 'nom': 'ECOLE PK 14 -4', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-309', 'nom': 'ECOLE PK 14 -5', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-310', 'nom': 'ECOLE PK 14 -6', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-311', 'nom': 'ECOLE PK 14 -7', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-312', 'nom': 'ECOLE PK 14 -8', 'region': 'BALBALA', 'inscrits': '404'},
  {'id': 'BV-313', 'nom': 'ECOLE PK 14 -9', 'region': 'BALBALA', 'inscrits': '407'},
  {'id': 'BV-314', 'nom': 'ECOLE nitobe -1', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-315', 'nom': 'ECOLE nitobe -2', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-316', 'nom': 'ECOLE nitobe -3', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-317', 'nom': 'ECOLE nitobe -4', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-318', 'nom': 'ECOLE nitobe -5', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-319', 'nom': 'ECOLE nitobe -6', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-320', 'nom': 'ECOLE nitobe -7', 'region': 'BALBALA', 'inscrits': '384'},
  {'id': 'BV-321', 'nom': 'ECOLE nitobe -8', 'region': 'BALBALA', 'inscrits': '387'},
  {'id': 'BV-322', 'nom': 'ECOLE PK 20 -1', 'region': 'BALBALA', 'inscrits': '307'},
  {'id': 'BV-323', 'nom': 'ECOLE PK 20 -2', 'region': 'BALBALA', 'inscrits': '307'},
  {'id': 'BV-324', 'nom': 'ECOLE PK 20 -3', 'region': 'BALBALA', 'inscrits': '308'},
  {'id': 'BV-325', 'nom': 'ECOLE BARWAQO I -1', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-326', 'nom': 'ECOLE BARWAQO I -2', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-327', 'nom': 'ECOLE BARWAQO I -3', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-328', 'nom': 'ECOLE BARWAQO I -4', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-329', 'nom': 'ECOLE BARWAQO I -5', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-330', 'nom': 'ECOLE BARWAQO I -6', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-331', 'nom': 'ECOLE BARWAQO I -7', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-332', 'nom': 'ECOLE BARWAQO I -8', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-333', 'nom': 'ECOLE BARWAQO I -9', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-334', 'nom': 'ECOLE BARWAQO I -10', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-335', 'nom': 'ECOLE BARWAQO I -11', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-336', 'nom': 'ECOLE BARWAQO I -12', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-337', 'nom': 'ECOLE BALBALA VI -1', 'region': 'BALBALA', 'inscrits': '393'},
  {'id': 'BV-338', 'nom': 'ECOLE BALBALA VI -2', 'region': 'BALBALA', 'inscrits': '395'},
  {'id': 'BV-339', 'nom': 'ECOLE BALBALA VI -3', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-340', 'nom': 'ECOLE BALBALA VI -4', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-341', 'nom': 'ECOLE BALBALA VI -5', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-342', 'nom': 'ECOLE BALBALA VI -6', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-343', 'nom': 'ECOLE BALBALA VI -7', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-344', 'nom': 'ECOLE BALBALA VI -8', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-345', 'nom': 'ECOLE BALBALA VI -9', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-346', 'nom': 'ECOLE BALBALA VI -10', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-347', 'nom': 'ECOLE BALBALA VI -11', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-348', 'nom': 'ECOLE BALBALA VI -12', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-349', 'nom': 'ECOLE BALBALA VI -13', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-350', 'nom': 'ECOLE BALBALA VI -14', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-351', 'nom': 'CES FUKUZAWA I -1', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-352', 'nom': 'CES FUKUZAWA I -2', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-353', 'nom': 'CES FUKUZAWA I -3', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-354', 'nom': 'CES FUKUZAWA I -4', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-355', 'nom': 'CES FUKUZAWA I -5', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-356', 'nom': 'CES FUKUZAWA I -6', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-357', 'nom': 'CES FUKUZAWA I -7', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-358', 'nom': 'CES FUKUZAWA I -8', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-359', 'nom': 'CES FUKUZAWA I -9', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-360', 'nom': 'CES FUKUZAWA I -10', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-361', 'nom': 'CES FUKUZAWA I -11', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-362', 'nom': 'CES FUKUZAWA I -12', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-363', 'nom': 'CES FUKUZAWA I -13', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-364', 'nom': 'CES FUKUZAWA I -14', 'region': 'BALBALA', 'inscrits': '418'},
  {'id': 'BV-365', 'nom': 'CES FUKUZAWA I -15', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-366', 'nom': 'CES FUKUZAWA I -16', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-367', 'nom': 'CES FUKUZAWA I -17', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-368', 'nom': 'CES FUKUZAWA I -18', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-369', 'nom': 'CES FUKUZAWA I -19', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-370', 'nom': 'CES FUKUZAWA I -20', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-371', 'nom': 'CES FUKUZAWA I -21', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-372', 'nom': 'CES FUKUZAWA I -22', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-373', 'nom': 'CES FUKUZAWA I -23', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-374', 'nom': 'CES FUKUZAWA I -24', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-375', 'nom': 'CES FUKUZAWA I -25', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-376', 'nom': 'CES FUKUZAWA I -26', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-377', 'nom': 'CEM BARWAQO -1', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-378', 'nom': 'CEM BARWAQO -2', 'region': 'BALBALA', 'inscrits': '399'},
  {'id': 'BV-379', 'nom': 'CEM BARWAQO -3', 'region': 'BALBALA', 'inscrits': '406'},
  {'id': 'BV-380', 'nom': 'CEM BARWAQO -4', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-381', 'nom': 'CEM BARWAQO -5', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-382', 'nom': 'CEM BARWAQO -6', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-383', 'nom': 'CEM BARWAQO -7', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-384', 'nom': 'CEM BARWAQO -8', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-385', 'nom': 'CEM BARWAQO -9', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-386', 'nom': 'CEM BARWAQO -10', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-387', 'nom': 'CEM BARWAQO -11', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-388', 'nom': 'CEM BARWAQO -12', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-389', 'nom': 'CEM BARWAQO -13', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-390', 'nom': 'CEM BARWAQO -14', 'region': 'BALBALA', 'inscrits': '388'},
  {'id': 'BV-391', 'nom': 'CEM BARWAQO -15', 'region': 'BALBALA', 'inscrits': '392'},
  {'id': 'BV-392', 'nom': 'ECOLE TOUR-OUSBO I -1', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-393', 'nom': 'ECOLE TOUR-OUSBO I -2', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-394', 'nom': 'ECOLE TOUR-OUSBO I -3', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-395', 'nom': 'ECOLE TOUR-OUSBO I -4', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-396', 'nom': 'ECOLE TOUR-OUSBO I -5', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-397', 'nom': 'ECOLE TOUR-OUSBO I -6', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-398', 'nom': 'ECOLE TOUR-OUSBO I -7', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-399', 'nom': 'ECOLE TOUR-OUSBO I -8', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-400', 'nom': 'ECOLE TOUR-OUSBO I -9', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-401', 'nom': 'ECOLE TOUR-OUSBO I -10', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-402', 'nom': 'ECOLE TOUR-OUSBO I -11', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-403', 'nom': 'ECOLE TOUR-OUSBO I -12', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-404', 'nom': 'ECOLE TOUR-OUSBO I -13', 'region': 'BALBALA', 'inscrits': '398'},
  {'id': 'BV-405', 'nom': 'ECOLE TOUR-OUSBO I -14', 'region': 'BALBALA', 'inscrits': '407'},
  {'id': 'BV-406', 'nom': 'ECOLE HAYABLEY -1', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-407', 'nom': 'ECOLE HAYABLEY -2', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-408', 'nom': 'ECOLE HAYABLEY -3', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-409', 'nom': 'ECOLE HAYABLEY -4', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-410', 'nom': 'ECOLE HAYABLEY -5', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-411', 'nom': 'ECOLE HAYABLEY -6', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-412', 'nom': 'ECOLE HAYABLEY -7', 'region': 'BALBALA', 'inscrits': '417'},
  {'id': 'BV-413', 'nom': 'ECOLE HAYABLEY -8', 'region': 'BALBALA', 'inscrits': '421'}
];
